blogicum/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name ='index'),
    path('posts/<int:id>/', views.post_detail, name = 'post_detail'),
    path('category/<slug:category_slug>/', views.category_posts, name ='category_posts'),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('blog.urls')),
]

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('pages/about/', views.about, name = 'about'),
    path('pages/rules/', views.rules, name = 'rules'),
]

blogicum/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Category(models.Model):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Описание')
    slug = models.SlugField(unique=True, verbose_name='Идентификатор', help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано', help_text='Снимите галочку, чтобы скрыть публикацию.')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')

    class Meta:
        verbose_name='категория'
        verbose_name_plural='Категории'

    def __str__(self):
        return self.title

class Location(models.Model):
    name = models.CharField(max_length=256, verbose_name='Название места')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')

    class Meta:
        verbose_name='местоположение'
        verbose_name_plural='Местоположения'
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(verbose_name='Дата и время публикации', help_text='Если установить дату и время в будущем — можно делать отложенные публикации.')
    author = models.ForeignKey( User, on_delete=models.CASCADE, related_name='posts', verbose_name='Автор публикации')
    location = models.ForeignKey( Location, on_delete=models.SET_NULL, null=True, related_name='posts', verbose_name='Местоположение')
    category = models.ForeignKey( Category, on_delete=models.SET_NULL, null=True, related_name='posts', verbose_name='Категория')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')

    class Meta:
        verbose_name='публикация'
        verbose_name_plural='Публикации'
    def __str__(self):
        return self.title

blogicum/pages/models.py
from django.db import models

# Create your models here.

blogicum/blog/views.py
from lib2to3.fixes.fix_input import context
from pydoc import locate

from django.shortcuts import render, get_object_or_404
from unicodedata import category

from. models import Post, Category
from datetime import datetime

def posts():
    return Post.objects.select_related(
        'location',
        'author',
        'category'
    ).filter(
        is_published=True,
        category__is_published=True,
        pub_date__lte=datetime.today()
    )


def index(request):
    template_name = 'blog/index.html'
    context = {'post_list': posts()[:5]}
    return render(request, template_name, context)

def category_posts(request, category_slug):
    category = get_object_or_404(
        Category,
        slug = category_slug,
        is_published=True
    )
    context = {
        'category': category,
        'post_list': posts().filter(category=category)
    }
    template_name = 'blog/category.html'
    return render(request, template_name, context)

def post_detail(request, id):
    post = get_object_or_404(posts(), id=id)
    context = {
        'post': post
    }
    template_name = 'blog/detail.html'
    return render(request, template_name, context)

blogicum/pages/views.py
from django.shortcuts import render

def about(request):
    template_name = 'pages/about.html'
    return render(request, template_name)

def rules(request):
    template_name = 'pages/rules.html'
    return render(request, template_name)

blogicum/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
      {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
</html>

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории «{{ category.title }}»
{% endblock %}
{% block content %}
<h1>Публикации в категории «{{ category.title }}»</h1>
<p class="mb-5">{{ category.description }}</p>
{% for post in post_list %}
  <article class="mb-5">  
    {% include "includes/post_card.html" %}
  </article>   
{% endfor %}

{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
{{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }} |{% endif %} {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <article>
    <p>{{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
      <small>От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}</small></p>
    <h3>{{ post.title }}</h3>
    <p>{{ post.text|linebreaksbr }}</p>
  </article> 
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  <h1 class="mb-5">Лента записей</h1>
  {% for post in post_list %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
{% endblock %}

blogicum/templates/includes/category_link.html
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  «{{ post.category.title }}»
</a>

blogicum/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

blogicum/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}        
        <ul class="nav  nav-pills">
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'blog:index' %} active {% endif %}" href="{% url 'blog:index' %}">
              Лента записей
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'pages:about' %} active {% endif %}" href="{% url 'pages:about' %}">
              О проекте
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:rules' %} active {% endif %}" href="{% url 'pages:rules' %}">
              Наши правила
            </a>
          </li>
        </ul>
      {% endwith %}      
    </div>
  </nav> 
</header>

blogicum/templates/includes/post_card.html
<div class="card" style="width: 40rem;">
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">
      <small>
        {{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
        От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}
      </small>
    </h6>
    <p class="card-text">{{ post.text|truncatewords:10 }}</p>
    <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
  </div>
</div>

blogicum/templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <h1>О проекте</h1>
  <p>
    Блогикум — это дом для творческих людей. Это — сообщество людей, для которых 
    нет грани между ведением блога и дружбой в социальных сетях. 
  </p>
  <p>
    Дружба и рассказы о новых, неизведанных впечатлениях — вот 
    что вы найдете на нашем ресурсе.  Миллионы блогов по различным темам. 
    Путешествия, политики, развлечения, мода, мода, литература, дизайн и все 
    другие сферы человеческой деятельности. 
  </p>
  <p>
    Творчество, разнообразие и свобода взглядов и самовыражения — 
    основные черты наших пользователей.
  </p> 
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <h1>Наши ценности</h1>
  <p>
    <b>Cамовыражение.</b> У наших пользователей должна 
    быть возможность создать что-то своё, выразить себя, 
    свои мысли и чувства.
  </p>
  <p>
    <b>Многообразие.</b> Мы уважаем и приветствуем разные 
    мнения и культуры. Блогикум — это место, объединяющее 
    самых разных людей. Поделитесь своим уникальным взглядом на мир.  
  </p>
  <p>
    <b>Творчество.</b> Не важно, в какой области вы творите, 
    это может быть литература, дизайн, программирование. 
    Наши инструменты помогут вам раскрыть талант максимально 
    просто и комфортно.   
  </p>
  <p>
    <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне. 
    Делитесь своей информацией только с теми, кого выбрали. 
    Как и насколько засекречивать вашу личную информацию — 
    определяете вы и только вы.  
  </p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
      {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
</html>

templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории «{{ category.title }}»
{% endblock %}
{% block content %}
<h1>Публикации в категории «{{ category.title }}»</h1>
<p class="mb-5">{{ category.description }}</p>
{% for post in post_list %}
  <article class="mb-5">  
    {% include "includes/post_card.html" %}
  </article>   
{% endfor %}

{% endblock %}

templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
{{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }} |{% endif %} {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <article>
    <p>{{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
      <small>От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}</small></p>
    <h3>{{ post.title }}</h3>
    <p>{{ post.text|linebreaksbr }}</p>
  </article> 
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  <h1 class="mb-5">Лента записей</h1>
  {% for post in post_list %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
{% endblock %}

templates/includes/category_link.html
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  «{{ post.category.title }}»
</a>

templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}        
        <ul class="nav  nav-pills">
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'blog:index' %} active {% endif %}" href="{% url 'blog:index' %}">
              Лента записей
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'pages:about' %} active {% endif %}" href="{% url 'pages:about' %}">
              О проекте
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:rules' %} active {% endif %}" href="{% url 'pages:rules' %}">
              Наши правила
            </a>
          </li>
        </ul>
      {% endwith %}      
    </div>
  </nav> 
</header>

templates/includes/post_card.html
<div class="card" style="width: 40rem;">
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">
      <small>
        {{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
        От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}
      </small>
    </h6>
    <p class="card-text">{{ post.text|truncatewords:10 }}</p>
    <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
  </div>
</div>

templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <h1>О проекте</h1>
  <p>
    Блогикум — это дом для творческих людей. Это — сообщество людей, для которых 
    нет грани между ведением блога и дружбой в социальных сетях. 
  </p>
  <p>
    Дружба и рассказы о новых, неизведанных впечатлениях — вот 
    что вы найдете на нашем ресурсе.  Миллионы блогов по различным темам. 
    Путешествия, политики, развлечения, мода, мода, литература, дизайн и все 
    другие сферы человеческой деятельности. 
  </p>
  <p>
    Творчество, разнообразие и свобода взглядов и самовыражения — 
    основные черты наших пользователей.
  </p> 
{% endblock %}

templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <h1>Наши ценности</h1>
  <p>
    <b>Cамовыражение.</b> У наших пользователей должна 
    быть возможность создать что-то своё, выразить себя, 
    свои мысли и чувства.
  </p>
  <p>
    <b>Многообразие.</b> Мы уважаем и приветствуем разные 
    мнения и культуры. Блогикум — это место, объединяющее 
    самых разных людей. Поделитесь своим уникальным взглядом на мир.  
  </p>
  <p>
    <b>Творчество.</b> Не важно, в какой области вы творите, 
    это может быть литература, дизайн, программирование. 
    Наши инструменты помогут вам раскрыть талант максимально 
    просто и комфортно.   
  </p>
  <p>
    <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне. 
    Делитесь своей информацией только с теми, кого выбрали. 
    Как и насколько засекречивать вашу личную информацию — 
    определяете вы и только вы.  
  </p>
{% endblock %}